export const toriQuotes = [
  "Are you a good witch or a sandwich?",
  "Can we try it again without the physical assault?",
  "Cat! You weren't supposed to tell her that.",
  "Did you just call me Toro?",
  "Eat your pants!",
  "Everybody sweats.",
  "He's a puppet, he can't pee.",
  "Honestly, I wouldn't love it.",
  "I am a police officer! Would you like some Raisin Bran?",
  "I know what I meant.",
  "I like waffles.",
  "I see through your little plan.",
  "I swear, I thought I had it on vibrate.",
  "I thought he was homeless.",
  "I'm alone.",
  "It was 1934 when my husband left me... alone. Living on the prairie was a dreary existence. No telephone, no radio, only a large majestic bird with whom I shared my feelings. One day when I was feeling low, I said to him, 'Oh, bird. You can fly. You can soar miles from this lonely place, and yet you stay. Why?' And apparently, that question rang true, for that afternoon my bird left. And so went my spirit.",
  "It's not my fault!",
  "It's so hot!",
  "Let me have you on the couch.",
  "Love me? Love me now? Yeah you do. Come on, give Tori a squeeze.",
  "My throat is an instrument, I'm a throat player.",
  "Oh my god. I am so hot.",
  "That's not my head!",
  "Try not to swallow each other.",
  "Uhh...",
  "Wait! So neither of you are coming with us tomorrow night to the museum of large bones?",
  "We're not going out!",
  "Well, hello.",
  "Yo, yo, yo! Whattayaknow!",
  "You could... wazz.",
  "You know I'm half Latina.",
  "You're not supposed to hit her.",
];
